// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxplkbopynommqzjuuag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4cGxrYm9weW5vbW1xemp1dWFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MjczOTUsImV4cCI6MjA3MzIwMzM5NX0.3VPFpAHN4R4tVXJqaVgaaGxpfb91qyQeKdYv5BGZ3PU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});